task: update_media
host: "https://islandora.traefik.me/"
username: admin
password: password
input_csv: update_media.csv
# media_use_tid is optional, it defaults to "Original file".
media_use_tid: 18
standalone_media_url: true